### ISSUE TITLE
ScrapeHandler is internal (instead of public), preventing usage without MetricServer

### ISSUE THREAD

**Issue by fortinmike** [andrasm/prometheus-net#10]
I'm trying to use prometheus-net in an ASP.NET MVC app and want to expose metrics directly in one of my controllers instead of using MetricServer. It seems like a combination of Registry and ScrapeHandler would do the job, but ScrapeHandler is internal so we can't use it externally.

Unless I've misunderstood how external usage is supposed to work, it looks like this was simply forgotten in commit 948e9f66622e9acebf3de112cab61579276f8b74.

Any help would be appreciated!

**Comment by qed-** [comment]
It's true that you will need a MetricServer but ProcessScrapeRequest() is public, and you don't have to call Start() if you have your own web server around.

That said I don't see any problem with making ScrapeHandler public.

**Comment by fortinmike** [comment]
Oh I see, thanks for the guidance! I'll use the `ProcessScrapeRequest()` method in the meantime, but I think making ScrapeHandler public like the other classes beside it would be best.

Instantiating a`MetricServer` with a port and other network-related parameters is redundant and misleading when embedding prometheus-net in a web server. May I also suggest adding a "Using prometheus-net without the embedded server" section in the readme? I think this is a relatively common use case.

Thanks for the library, by the way!
