### ISSUE TITLE
MetricServer.Stop cause Topshelf service invoke stop handler twice.

### ISSUE THREAD

**Issue by easyalgoltd** [andrasm/prometheus-net#15]
Hi.

I use MetricServer in my topshelf-based windows service.
There is a handler of service stop where I call MetricServer.Stop, after that stop handler is invoked again.

Have you ever faced with such issue?

**Comment by easyalgoltd** [comment]
I've made some tests and it seems that the problem is in the following code (MetricServer.cs):
`scheduler.Schedule(repeatAction => _httpListener.BeginGetContext(ar =>`

_httpListener might be already disposed.

**Comment by andrasm** [comment]
Thanks for reporting, this is now fixed in v1.1.1
