### ISSUE TITLE
Push Gateway support

### ISSUE THREAD

**Issue by amw2104** [andrasm/prometheus-net#19]
Hi,

We are considering using your library to instrument a B2C .NET Desktop client. I believe we will need to be able to use the Push To Gateway mechanism since our users application sessions are short lived and we cannot expect the prometheus server to scrape hundreds of thousands of clients across our customer base. Do you have any plans to add support for Push To Gateway in this library?

Andrew

**Comment by andrasm** [comment]
Hi Andrew,

I had no concrete plans to add push gateway support but a "proper" Prometheus client lib should really support this functionality, so I'm inclined to add this. I'm a bit busy these days but can look into this in the next couple of weeks if you really need this. Are you sure this is the best option for your use case? Metric timestamps could be confusing (push ts vs scrape ts)

Regards
Andras

**Comment by amw2104** [comment]
Hi Andras,

Thank you for the fast response. I decided to checkout InfluxDB first, so I may not end up needing it. If I decide to go with Prometheus instead, then I'll ping you on this thread again.

Andrew
