### ISSUE TITLE
Thoughts on supporting the ability to turn this on or off?

### ISSUE THREAD

**Issue by sstorie** [andrasm/prometheus-net#30]
I'm starting to use this in our WebAPI applications using OWIN, and so far it's working nicely. I'm instrumenting both the OWIN pipeline and our internal API code, but I'm finding myself wanting the ability to toggle this off or on via some configuration. Let's say that for whatever reason I want to suddenly turn off instrumentation all together, have you thought of how you might address that with this library?

Given how pervasive the instrumentation code itself is, one though I had was to support providing a "null" version of the metric related objects that provide the required methods for all the calling code, but just don't do anything. However, this would (at the very least) require interfaces around the objects to support injecting alternate versions (the real one vs the null on based on some condition). Right now I'm using an instance of the `MetricFactory` in my code to get counters, histograms, etc, so I'd need to provide an alternate version of the factory first that in-turn provided alternate versions of the Counter, Histogram, etc classes.

Have you come across the need for this, or thought about how you might address this scenario?

**Comment by dustinchilson** [comment]
What part do you want to turn off? If you don't start the MetricServer or the MetricPusher it shouldn't really do anything other than use a bit of ram.

I built and use this https://github.com/dustinchilson/PrometheusNet.Owin and just wrap the app.UsePrometheusServer(); in an app setting.

**Comment by sstorie** [comment]
Yeah, I was just thinking if we roll this out in a production setting, and say something goes wrong with the metric related code (who knows what). It'd be nice to have a switch I could flip to effectively disable all the instrumentation code (not just the server component) without releasing a new version of my own code that had it all removed.

Imagine a feature toggle that would let you keep the instrumentation code there, but temporarily shut both the collection of each metric and the scrapable endpoint off.

**Comment by sstorie** [comment]
If it's not clear I'm not implying that this library itself should provide this ability, but if it exposed interfaces around some of these objects it might be possible to build a feature toggle around it.

@dustinchilson btw, thanks for writing that OWIN middleware. I used your code and adapted it slightly for our internal use.

**Comment by sandersaares** [comment]
This sounds like it might require a lot of work and add a layer to the system for a somewhat dubious benefit. For the time being, I am closing this as a rejected feature request. However, if this remains something of significant interest to you, please propose the specific changes you would like to see and reopen the issue for further discussion.
