### ISSUE TITLE
.Net Core support

### ISSUE THREAD

**Issue by mribichich** [andrasm/prometheus-net#31]
Hi there, are you planning on supporting .NET Core?

thanks!

**Comment by andrasm** [comment]
Hi - yes. Actually there is already a pull request for this, will merge that sometime in the next 3 weeks.

**Comment by ceepeeuk** [comment]
Hi,

I recently took a look at the dotnet.core pull request and noticed that it didn't support netstandard 1.6, so I have forked and updated accordingly.

https://github.com/ceepeeuk/prometheus-net

If you want I can add a pull request? I'd like to make this available in nuget in case its of use to anyone else? Not sure how best to approach this, any thoughts? More than happy for you to do this or I can do it as prometheus-net-core.

Let me know,
cheers.

**Comment by andrasm** [comment]
Hi Chris,

Best would be if you could merge this directly to master, I just couldn't find the time to do this myself. I may need to tweak travis-ci a bit.

Thanks,
Andras

**Comment by ceepeeuk** [comment]
Hi Andras,

Happy to do that, but it would break on <=4.5, as I had to remove MetricServer, as there really is not equivalent to HttpListener in dotnet core. Kestrel serves a similar purpose, but could not really be used as such here.

Thats why I was thinking it would be more appropriate to maintain two versions - prometheus-net and prometheus-net-core.

Can you think of a way of avoiding this?

chris

**Comment by stefc** [comment]
What about this project? 
[https://github.com/robertsundstrom/HttpListener]

**Comment by antonichoudhuri** [comment]
@ceepeeuk @andrasm Has there been any change here? I would also like to use prometheus on dotnet core.

**Comment by andrasm** [comment]
No sorry - I'm swamped with other stuff. 

@ceepeeuk: I have no objections to having a separate prometheus-net-core version if there is no better option. 

But actually, I'm happy to transfer the ownership of this project if somebody volunteers to take over - I cannot see myself having more time in the future.

**Comment by MihaMarkic** [comment]
@ceepeeuk Why do you think Kestrel can't be used? To bloated? Also, why separate version for .netcore? If MetricsServer is a problem, let's just implement it differently?

**Comment by MihaMarkic** [comment]
Also, there is a pull request 5c9d3a42be3ce7980ec7f08b8b215cb6ea75c7d7 that adds middleware that could be used in combination with kestrel as well.

**Comment by tbolon** [comment]
The simplest approach should by to wait for .NET Core 2.0 which will port [httplistener](https://github.com/dotnet/corefx/issues/11793), conforming netstandard2.0.

**Comment by dmirmilshteyn** [comment]
I needed a .net-core compatible Prometheus client, so here's my attempt (with the help of the work done by @MihaMarkic and @ceepeeuk): https://github.com/dmirmilshteyn/prometheus-net/tree/netcore

I've tried to minimize any invasive changes. I consolidated the various projects for different targets into a single project, and using the new multi-targeting features, it outputs assemblies for net40, net45, and netstandard1.3. I haven't changed any dependencies (net40 still uses Rx 2.25, net45 and netstandard1.3 use System.Reactive). The only exception to that was updating protobuf-net to a version that supports all three targets.

There were two cases where features weren't available on netstandard: WebClient and HttpListener. Netstandard doesn't support either, so I switched to HttpClient and Kestrel *for netstandard only*. WebClient and HttpListener are still used for net40 and net45, guarded with minor usage of #ifdef's.

Tests also were consolidated, using an updated version of NUnit. The Should library that's used in the current tests is deprecated and has been renamed to Shouldly. I've updated tests to use that. Some methods from that library were renamed (ie ShouldEqual to ShouldBe), but nothing major. 

The deploy_nuget.bat script was updated to use the dotnet cli tools.

Long-term wise, I think Kestrel should be used for platforms that support it. While HttpListener is being ported to netstandard2.0, based on some of the discussions around it on the corefx repo, it has been deprecated and only available to help compatibility. This likely means it won't see much work done on it (in terms of improving performance on different platforms), where most of their efforts will go into Kestrel. 

@andrasm can you review this?

**Comment by andrasm** [comment]
Hi Daniel - this looks good to me. 

Not being an expert in the area I don't have an opinion on Kestrel vs HttpListener, so I'm happy to accept the decision described above, especially that backward compatibility is ensured by the ifdefs.

**Comment by phnx47** [comment]
I also made the version, but I used the extensions for Owin: https://github.com/phnx47/Prometheus.Client.

**Comment by dguerin** [comment]
Hi all, very eager to use this for a number of microservices I work on. What's left to be done on this? It might be something I could help with.

**Comment by andrasm** [comment]
Hi - was about to merge/publish this now but just realised I don't have the toolset installed yet to test/build this just now (working on a limited portable hotspot so can't download anything big). 

I will have proper access around after Eastern - but to speed this up am happy to give push access and can upload to nuget if you can build it.

**Comment by iremA** [comment]
I'll also be happy to help

**Comment by dmirmilshteyn** [comment]
@andrasm That would be fine with me. I'll have some time to do this and build a binary this weekend

**Comment by iremA** [comment]
@andrasm @dmirmilshteyn any improvement there?

**Comment by Karnich** [comment]
very excited for .net core support.. +1

**Comment by flavio1110** [comment]
very excited for .net core support.. +2 
Any idea when the PR#50 will be merged?

**Comment by andrasm** [comment]
Sorry for the long silence, this's now been merged. Will be pushing a pre-release nuget version shortly, can people please confirm if that works OK on .net core?

**Comment by a-h** [comment]
I've run a quick tyre kick on .NET Core, my scrape returns:

```
# HELP process_windows_private_bytes Process private memory size
# TYPE process_windows_private_bytes GAUGE
process_windows_private_bytes 0
# HELP dotnet_collection_errors_total Total number of errors that occured during collections
# TYPE dotnet_collection_errors_total COUNTER
# HELP process_windows_num_threads Total number of threads
# TYPE process_windows_num_threads GAUGE
process_windows_num_threads 25
# HELP process_cpu_seconds_total Total user and system CPU time spent in seconds
# TYPE process_cpu_seconds_total COUNTER
process_cpu_seconds_total 380.1714067
# HELP dotnet_totalmemory Total known allocated memory
# TYPE dotnet_totalmemory GAUGE
dotnet_totalmemory 11339704
# HELP process_windows_processid Process ID
# TYPE process_windows_processid GAUGE
process_windows_processid 53386
# HELP process_start_time_seconds Start time of the process since unix epoch in seconds
# TYPE process_start_time_seconds GAUGE
process_start_time_seconds 1497278899.81909
# HELP dotnet_collection_count_total GC collection count
# TYPE dotnet_collection_count_total COUNTER
dotnet_collection_count_total{generation="1"} 0
dotnet_collection_count_total{generation="0"} 0
dotnet_collection_count_total{generation="2"} 0
# HELP get_called The number of times that get was called.
# TYPE get_called COUNTER
get_called 14
# HELP process_windows_working_set Process working set
# TYPE process_windows_working_set GAUGE
process_windows_working_set 46170112
# HELP process_windows_virtual_bytes Process virtual memory size
# TYPE process_windows_virtual_bytes GAUGE
process_windows_virtual_bytes 23079096320
```

I'm running .NET Core on Linux, so not sure where the _windows_ metrics are coming from. 😂

**Comment by kristofferjansson** [comment]
@dmirmilshteyn @andrasm 
Been trying this on a asp.net core project and I want to expose the /metrics endpoint on the same host and port as the application. I can't get this to work with the MetricServer.Kestrel implementation by just instantiating and starting the MetricServer on the same port as the app.

Should this be possible?

I think I would prefer using a middleware that handles the /metrics requests, something like in this PR https://github.com/andrasm/prometheus-net/commit/5c9d3a42be3ce7980ec7f08b8b215cb6ea75c7d7

Pretty easy to do yourself but it is something that maybe should be included in this project?

**Comment by ahoka** [comment]
@kristofferjansson We just open sourced a library that we use to measure metrics and store them in Prometheus: https://github.com/nexogen-international/Nexogen.Libraries.Metrics

**Comment by abhishekdeo** [comment]
Hey! New to .NET Core and trying to use this NuGet. Getting following errors when I am using for .NET core and .NET standard. Is this NuGet not compatible with .NET Core 2.0? If yes is there any plan to upgrade?

Warning	NU1701	Package 'prometheus-net 1.3.5' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETCoreApp,Version=v2.0'. This package may not be fully compatible with your project.	
Warning	NU1701	Package 'prometheus-net 1.3.5' was restored using '.NETFramework,Version=v4.6.1' instead of the project target framework '.NETStandard,Version=v2.0'. This package may not be fully compatible with your project.

**Comment by sandersaares** [comment]
@kristofferjansson and all, prometheus-net middleware for ASP.NET Core is coming in v2.0. Preview packages available within a few weeks.

**Comment by sandersaares** [comment]
ASP.NET Core middleware is now available in version 2.0. Please try the preview package and let me know if something seems not right. I will close the issue as resolved for now but do not hesitate to reopen or file a new one.

The preview version carries the label 2.0.0-pre-002968-9fcb8aa and is published as two packages:
 [prometheus-net](https://www.nuget.org/packages/prometheus-net/2.0.0-pre-002968-9fcb8aa) with the main classes and [prometheus-net.AspNetCore](https://www.nuget.org/packages/prometheus-net.AspNetCore/2.0.0-pre-002968-9fcb8aa) with those that take an ASP.NET Core dependency.

A stable version of the package can be expected within a month if no surprises come up during testing.

**Comment by dotnetdude** [comment]
Just tried the .net standard version  using push gateway and gauge metrics and it failed. full framework version working fine. waiting for the stable version.

**Comment by sandersaares** [comment]
Thanks for giving it a try! Please submit an issue report detailing how to reproduce the problem you encountered.

**Comment by dotnetdude** [comment]
Thanks @sandersaares  added details here #75
