### ISSUE TITLE
Unlabelled histogram is always created by default

### ISSUE THREAD

**Issue by sia-s** [andrasm/prometheus-net#39]
When creating histograms with labels, the unlabeled instance is always reported even if you never observe any value without labels. The culprit is following line in Histogram's constructor:
```csharp
            Unlabelled.Init(this, LabelValues.Empty);
```

**Comment by sandersaares** [comment]
The difficulty comes from drawing a distinction between "the unlabeled histogram is not wanted" and "the unlabeled histogram is wanted but has not observed any values yet". Prometheus best practices recommend always exporting metrics for any series that may exist:

> Avoid missing metrics
> Time series that are not present until something happens are difficult to deal with, as the usual simple operations are no longer sufficient to correctly handle them. To avoid this, export 0 (or NaN, if 0 would be misleading) for any time series you know may exist in advance.
> 
> Most Prometheus client libraries (including Go, Java, and Python) will automatically export a 0 for you for metrics with no labels.

Does the current implementation cause any additional difficulties beyond just generating a useless set of metrics?

**Comment by sandersaares** [comment]
Comparing with what is done for other types of metrics in prometheus-net, however, I see that this behavior deviates from other metrics. Therefore, it should indeed be unified so that the unlabelled histogram is not created needlessly. The fix will be included in v2.0.

**Comment by sandersaares** [comment]
Fixed in v2 branch. Preview NuGet package should be available within a week. I will leave the issue open until the package is ready.
