### ISSUE TITLE
idea: Bucket values must be increasing - why throw?

### ISSUE THREAD

**Issue by a-h** [andrasm/prometheus-net#54]
If there's a check to see whether the items are sorted or not, why not just apply a sort instead? 

```C#
throw new ArgumentException("Bucket values must be increasing");
````

**Comment by brian-brazil** [comment]
If they're out of order the chances are that the user made a typo and should be alerted to that fact, as I'd expect ~everyone to attempt to provide them in order.

**Comment by sandersaares** [comment]
Rationale above makes sense. Closing as by design.
