### ISSUE TITLE
not thread safe

### ISSUE THREAD

**Issue by pcorazao** [andrasm/prometheus-net#60]
when the library is used in parallel the /metrics endpoint is iterating over a collection of metrics and other threads might be adding to the collection causing a collection modified while iterating exception.

**Comment by pcorazao** [comment]
singleton around the server creation and init of the port with thread safe mutex around the singleton instance.

**Comment by bweston92** [comment]
Is this still the case? I want to run a metrics pusher in one thread and build the metrics in another thread.

**Comment by sandersaares** [comment]
Can you provide a specific code example that showcases this issue?

**Comment by sandersaares** [comment]
Review of the relevant source code did not indicate any obvious concurrency issues. If this remains an issue, please provide example code that demonstrates the problem and reopen the issue.
