### ISSUE TITLE
Current nuspec includes System.Reactive.* in nuget lib dir

### ISSUE THREAD

**Issue by SimonCropp** [andrasm/prometheus-net#61]
this should be redundant since there is already a nuget dependency on System.Reactive ?
![image](https://user-images.githubusercontent.com/122666/28909224-de9bfba4-786a-11e7-9bde-d67f6f1a815f.png)

**Comment by SimonCropp** [comment]
same goes for protobuf

**Comment by SimonCropp** [comment]
@andrasm if u can point me to where the nuspec information is derived from i can send a PR

**Comment by sandersaares** [comment]
Fix scheduled for v2.0.

**Comment by sandersaares** [comment]
This issue should be resolved in version 2.0. Please try the preview package and let me know if something seems not right.

The preview version carries the label 2.0.0-pre-002968-9fcb8aa and is published as two packages:
 [prometheus-net](https://www.nuget.org/packages/prometheus-net/2.0.0-pre-002968-9fcb8aa) with the main classes and [prometheus-net.AspNetCore](https://www.nuget.org/packages/prometheus-net.AspNetCore/2.0.0-pre-002968-9fcb8aa) with those that take an ASP.NET Core dependency.

A stable version of the package can be expected within a month if no surprises come up during testing.
