### ISSUE TITLE
No method is provided to indicate failed scrapes

### ISSUE THREAD

**Issue by godefroi** [andrasm/prometheus-net#64]
As noted here: https://prometheus.io/docs/instrumenting/writing_exporters/#failed-scrapes the preferred way to indicate failed scrapes is to return a 5xx error. Currently, prometheus-net provides no way to do that, as all exceptions are swallowed.

**Comment by godefroi** [comment]
A specific exception we could throw to cause a 5xx error to be returned would be perfect.

**Comment by sandersaares** [comment]
I would like to understand the desired use case in more depth. What is the type of metric being collected and what is a failure in this context? What do you expect the data arriving in Prometheus to be before/during/after a failure for a given metric?

**Comment by godefroi** [comment]
For example, say I have an exporter running as a separate executable, and this exporter uses on-demand collectors to gather information about the system being monitored. In the case where the system being monitored is down, I must use an additional time series (call it `mysystem_up`) to indicate that. If I could indicate a failed scrape to Prometheus, then Prometheus' built-in `up` timeseries could do that for me.

**Comment by sandersaares** [comment]
I see. Yes, this sounds like a useful feature. It will be implemented in the v2 branch. Preview packages should be available soon, once v2 is merged to master after a thorough review.

**Comment by sandersaares** [comment]
This is now implemented in version 2.0. You can throw a `ScrapeFailedException` to signal a failed scrape (see the Tester project for an example). Please try the preview package and let me know if something seems not right.

The preview version carries the label 2.0.0-pre-002968-9fcb8aa and is published as two packages:
 [prometheus-net](https://www.nuget.org/packages/prometheus-net/2.0.0-pre-002968-9fcb8aa) with the main classes and [prometheus-net.AspNetCore](https://www.nuget.org/packages/prometheus-net.AspNetCore/2.0.0-pre-002968-9fcb8aa) with those that take an ASP.NET Core dependency.

A stable version of the package can be expected within a month if no surprises come up during testing.
