### ISSUE TITLE
`RegisterMetrics()` in `IOnDemandCollector` should provide a `MetricFactory` parameter

### ISSUE THREAD

**Issue by godefroi** [andrasm/prometheus-net#65]
I'm currently creating several exporters, most of which utilize `IOnDemandCollector` style metrics. This means that there are several steps that I have to go through to be successful:

1. I must create an instance of `ICollectorRegistry` (and the only provided implementation is the confusingly-named `DefaultCollectorRegistry`).
2. I must instantiate my `IOnDemandCollector` instance(s), providing my `ICollectorRegistry` instance to the constructor.
3. I must cast the `ICollectorRegistry` to a `DefaultCollectorRegistry` in order to call the `RegisterOnDemandCollectors` method.
4. Inside my `RegisterMetrics()` method, I must use the previously-passed `ICollectorRegistry` instance to call `Metrics.WithCustomRegistry()` with.

This sequence would be somewhat simpler and less error-prone if either the `ICollectorRegistry` instance or a `MetricFactory` instance was passed into the `RegisterMetrics()` method.

**Comment by sandersaares** [comment]
Very true. Will be fixed in v2.0.

**Comment by sandersaares** [comment]
The requested feature has been added in version 2.0. Please try the preview package and let me know if something seems not right.

The preview version carries the label 2.0.0-pre-002968-9fcb8aa and is published as two packages:
 [prometheus-net](https://www.nuget.org/packages/prometheus-net/2.0.0-pre-002968-9fcb8aa) with the main classes and [prometheus-net.AspNetCore](https://www.nuget.org/packages/prometheus-net.AspNetCore/2.0.0-pre-002968-9fcb8aa) with those that take an ASP.NET Core dependency.

A stable version of the package can be expected within a month if no surprises come up during testing.
