### ISSUE TITLE
Ideas for 2.x

### ISSUE THREAD

**Issue by jdaigle** [andrasm/prometheus-net#69]
A few ideas for version 2 of the library.

**Consider splitting into a core library and separate server libraries.**

Right now the single package includes both the core metrics collection registry, scrape handler, and server implementations. The server implementations carry a lot of baggage which aren't always needed (System.Reactive, Microsoft.AspNetCore.Server, etc).

Consider a large project which may want to instrument some internal library; it would be convenient include a reference to a small core prometheus-net package that doesn't bring any other dependencies. But the "root" project, or projects, would then reference the appropriate hosting packages.

My proposal:

* Prometheus.Core (has no dependencies outside of .NET)
* Prometheus.Hosting.Core (ScrapeHandler and formatters)
* Prometheus.Hosting.HttpListener
* Prometheus.Hosting.Kestral

**Comment by sandersaares** [comment]
This makes a fair bit of sense. Will be scheduled for 2.0.

**Comment by sandersaares** [comment]
I reviewed the dependencies and it looks like the following package scheme makes the most sense in my eyes:

* prometheus-net - .NET Standard and "low cost" dependencies.
* prometheus-net.AspNetCore - all the ASP.NET Core and Kestrel features.

This will enable at least all the ASP.NET Core dependencies to be avoided for projects that do not use ASP.NET Core.

Reactive Extensions will be thrown out entirely - this dependency is only used to very minimal effect and it will do the library well to switch over to traditional TPL based async/await/Task scheduling.

protobuf-net dependency will remain for now, I think, as it is deeply embedded within prometheus-net. It is worth noting that the relevance of protobuf support is rather dubious in 2018, given that Prometheus 2.0 itself has completely dropped protobuf format. I doubt many people use it, as text+gzip seems to offer greater efficiency all around.

I have pushed a v2 branch with these reorganizations. It is still work in progress in other regards but I should have some v2.0 NuGet packages available for preview within January.

**Comment by sandersaares** [comment]
The restructuring described above is now complete in version 2.0. Please try the preview package and let me know if something seems not right.

The preview version carries the label 2.0.0-pre-002968-9fcb8aa and is published as two packages:
 [prometheus-net](https://www.nuget.org/packages/prometheus-net/2.0.0-pre-002968-9fcb8aa) with the main classes and [prometheus-net.AspNetCore](https://www.nuget.org/packages/prometheus-net.AspNetCore/2.0.0-pre-002968-9fcb8aa) with those that take an ASP.NET Core dependency.

A stable version of the package can be expected within a month if no surprises come up during testing.
