### ISSUE TITLE
Prometheus.MetricServer class is missing in net46 assembly

### ISSUE THREAD

**Issue by ivankaurov** [andrasm/prometheus-net#70]
v1.3.6-rc. The `Prometheus.MetricServer` class is not found when targeting .Net 4.6.1 or .Net 4.6. This is probably because `#if NET46` is missing in [MetricServer.HttpListener.cs](https://github.com/andrasm/prometheus-net/blob/master/prometheus-net/MetricServer.HttpListener.cs) class.

**Comment by sandersaares** [comment]
Thank you for mentioning. This will be corrected in 2.0.

**Comment by sandersaares** [comment]
This issue should be resolved in version 2.0. Please try the preview package and let me know if something seems not right.

The preview version carries the label 2.0.0-pre-002968-9fcb8aa and is published as two packages:
 [prometheus-net](https://www.nuget.org/packages/prometheus-net/2.0.0-pre-002968-9fcb8aa) with the main classes and [prometheus-net.AspNetCore](https://www.nuget.org/packages/prometheus-net.AspNetCore/2.0.0-pre-002968-9fcb8aa) with those that take an ASP.NET Core dependency.

A stable version of the package can be expected within a month if no surprises come up during testing.
